Traceback (most recent call last):
  File "tools/infer2.py", line 224, in <module>
    main(args)
  File "tools/infer2.py", line 213, in main
    draw([im_pil], labels, boxes, scores, 0.6)
  File "tools/infer2.py", line 141, in draw
    im.save(output_path)
  File "/leonardo/home/userexternal/adivicin/rtdetr/lib/python3.8/site-packages/PIL/Image.py", line 2563, in save
    fp = builtins.open(filename, "w+b")
PermissionError: [Errno 13] Permission denied: '/results_0.jpg'
